# Phase 3 — Customer Feature Engineering

# Phase 3 — Customer Feature Engineering

## AI-Powered Customer Segmentation
### Autoencoder + PyTorch + K-Means

### Objective

Transform the validated transactional data into a customer-level behavioral
feature matrix where one row represents one unique customer.

The feature set will capture:

- Recency, frequency, and monetary behavior
- Customer tenure
- Order and purchasing behavior
- Product and category diversity
- Seller diversity
- Freight behavior
- Payment behavior
- Customer satisfaction signals

The resulting customer feature matrix will be validated before preprocessing,
baseline clustering, and Autoencoder representation learning.

In [2]:
from pathlib import Path

import numpy as np
import pandas as pd

pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", lambda x: f"{x:,.2f}")

In [3]:
PROJECT_ROOT = Path.cwd().parent

DATA_RAW = PROJECT_ROOT / "data" / "raw"
DATA_PROCESSED = PROJECT_ROOT / "data" / "processed"

print("Project root:", PROJECT_ROOT)
print("Raw data:", DATA_RAW)
print("Processed data:", DATA_PROCESSED)
print("Raw exists:", DATA_RAW.exists())
print("Processed exists:", DATA_PROCESSED.exists())

Project root: C:\Users\amolm\Desktop\PROJECTS RESUME\Customer Segmentation
Raw data: C:\Users\amolm\Desktop\PROJECTS RESUME\Customer Segmentation\data\raw
Processed data: C:\Users\amolm\Desktop\PROJECTS RESUME\Customer Segmentation\data\processed
Raw exists: True
Processed exists: True

In [4]:
processed_files = list(DATA_PROCESSED.iterdir())

print("Number of processed files:", len(processed_files))

for file in processed_files:
    print(file.name)

Number of processed files: 1
order_analytics.parquet

In [5]:
phase2_notebook = (
    PROJECT_ROOT
    / "notebooks"
    / "01_data_understanding.ipynb"
)

print("Phase 2 notebook exists:", phase2_notebook.exists())

Phase 2 notebook exists: True

In [6]:
processed_files = list(DATA_PROCESSED.iterdir())

print("Number of processed files:", len(processed_files))

for file in processed_files:
    print(file.name)

Number of processed files: 1
order_analytics.parquet

In [7]:
# Load order_analytics

ORDER_ANALYTICS_PATH = (
    DATA_PROCESSED / "order_analytics.parquet"
)

order_analytics = pd.read_parquet(
    ORDER_ANALYTICS_PATH
)

print("Shape:", order_analytics.shape)

order_analytics.head()

Shape: (96478, 27)

,order_id,customer_id,order_status,order_purchase_timestamp,order_approved_at,order_delivered_carrier_date,order_delivered_customer_date,order_estimated_delivery_date,purchase_year,purchase_month,customer_unique_id,item_count,product_count,seller_count,merchandise_value,freight_value,avg_item_price,order_value,payment_value,payment_record_count,payment_method_count,max_installments,avg_installments,avg_review_score,review_record_count,category_count,products_with_category
0,e481f51cbdc54678b7cc49136f2d6af7,9ef432eb6251297304e76186b10a928d,delivered,2017-10-02 10:56:33,2017-10-02 11:07:15,2017-10-04 19:55:00,2017-10-10 21:25:13,2017-10-18,2017,2017-10,7c396fd4830fd04220f754e42b4e5bff,1,1,1,29.99,8.72,29.99,38.71,38.71,3.00,2.00,1.00,1.00,4.00,1.00,1,1
1,53cdb2fc8bc7dce0b6741e2150273451,b0830fb4747a6c6d20dea0b8c802d7ef,delivered,2018-07-24 20:41:37,2018-07-26 03:24:27,2018-07-26 14:31:00,2018-08-07 15:27:45,2018-08-13,2018,2018-07,af07308b275d755c9edb36a90c618231,1,1,1,118.70,22.76,118.70,141.46,141.46,1.00,1.00,1.00,1.00,4.00,1.00,1,1
2,47770eb9100c2d0c44946d9cf07ec65d,41ce2a54c0b03bf3443c3d931a367089,delivered,2018-08-08 08:38:49,2018-08-08 08:55:23,2018-08-08 13:50:00,2018-08-17 18:06:29,2018-09-04,2018,2018-08,3a653a41f6f9fc3d2a113cf8398680e8,1,1,1,159.90,19.22,159.90,179.12,179.12,1.00,1.00,3.00,3.00,5.00,1.00,1,1
3,949d5b44dbf5de918fe9c16f97b45f8a,f88197465ea7920adcdbec7375364d82,delivered,2017-11-18 19:28:06,2017-11-18 19:45:59,2017-11-22 13:39:59,2017-12-02 00:28:42,2017-12-15,2017,2017-11,7c142cf63193a1473d2e66489a9ae977,1,1,1,45.00,27.20,45.00,72.20,72.20,1.00,1.00,1.00,1.00,5.00,1.00,1,1
4,ad21c59c0840e6cb83a9ceb5573f8159,8ab97904e6daea8866dbdbc4fb7aad2c,delivered,2018-02-13 21:18:39,2018-02-13 22:20:29,2018-02-14 19:46:34,2018-02-16 18:17:02,2018-02-26,2018,2018-02,72632f0f9dd73dfee390c9b22eb56dd6,1,1,1,19.90,8.72,19.90,28.62,28.62,1.00,1.00,1.00,1.00,5.00,1.00,1,1

In [8]:
# Inspect the schema

order_analytics.info()

<class 'pandas.DataFrame'>
RangeIndex: 96478 entries, 0 to 96477
Data columns (total 27 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   order_id                       96478 non-null  str
 1   customer_id                    96478 non-null  str
 2   order_status                   96478 non-null  str
 3   order_purchase_timestamp       96478 non-null  datetime64[us]
 4   order_approved_at              96464 non-null  datetime64[us]
 5   order_delivered_carrier_date   96476 non-null  datetime64[us]
 6   order_delivered_customer_date  96470 non-null  datetime64[us]
 7   order_estimated_delivery_date  96478 non-null  datetime64[us]
 8   purchase_year                  96478 non-null  int32
 9   purchase_month                 96478 non-null  period[M]
 10  customer_unique_id             96478 non-null  str
 11  item_count                     96478 non-null  int64
 12  product_count                  96478 non-null  int64
 13  seller_count                   96478 non-null  int64
 14  merchandise_value              96478 non-null  float64
 15  freight_value                  96478 non-null  float64
 16  avg_item_price                 96478 non-null  float64
 17  order_value                    96478 non-null  float64
 18  payment_value                  96477 non-null  float64
 19  payment_record_count           96477 non-null  float64
 20  payment_method_count           96477 non-null  float64
 21  max_installments               96477 non-null  float64
 22  avg_installments               96477 non-null  float64
 23  avg_review_score               95832 non-null  float64
 24  review_record_count            95832 non-null  float64
 25  category_count                 96478 non-null  int64
 26  products_with_category         96478 non-null  int64
dtypes: datetime64[us](5), float64(11), int32(1), int64(5), period[M](1), str(4)
memory usage: 29.2 MB

In [9]:
print(order_analytics.columns.tolist())

['order_id', 'customer_id', 'order_status', 'order_purchase_timestamp', 'order_approved_at', 'order_delivered_carrier_date', 'order_delivered_customer_date', 'order_estimated_delivery_date', 'purchase_year', 'purchase_month', 'customer_unique_id', 'item_count', 'product_count', 'seller_count', 'merchandise_value', 'freight_value', 'avg_item_price', 'order_value', 'payment_value', 'payment_record_count', 'payment_method_count', 'max_installments', 'avg_installments', 'avg_review_score', 'review_record_count', 'category_count', 'products_with_category']

In [11]:
# Validate the loaded Phase 2 artifact

load_validation = pd.Series({
    "rows":
        len(order_analytics),

    "unique_orders":
        order_analytics["order_id"].nunique(),

    "unique_customers":
        order_analytics["customer_unique_id"].nunique(),

    "duplicate_order_ids":
        order_analytics["order_id"].duplicated().sum(),

    "missing_customer_ids":
        order_analytics["customer_unique_id"].isna().sum()
})

load_validation

rows                    96478
unique_orders           96478
unique_customers        93358
duplicate_order_ids         0
missing_customer_ids        0
dtype: int64

In [12]:
# Verify timestamps

# We specifically need order_purchase_timestamp for Recency and Tenure.

pd.Series({
    "purchase_timestamp_dtype":
        str(order_analytics["order_purchase_timestamp"].dtype),

    "first_purchase":
        order_analytics["order_purchase_timestamp"].min(),

    "last_purchase":
        order_analytics["order_purchase_timestamp"].max(),

    "missing_purchase_timestamp":
        order_analytics["order_purchase_timestamp"].isna().sum()
})

purchase_timestamp_dtype           datetime64[us]
first_purchase                2016-09-15 12:16:38
last_purchase                 2018-08-29 15:00:37
missing_purchase_timestamp                      0
dtype: object

Step 4: Define the Customer Feature Specification

Before coding the aggregation, we need to decide what the model should know about each customer.

We should not feed all 27 columns into the Autoencoder. IDs, raw timestamps, order status,
and redundant variables are not automatically useful ML features.

Feature families

## Customer Feature Specification

The order-level analytical dataset is transformed into one behavioral profile
per `customer_unique_id`.

Features are organized into behavioral families rather than including every
available column.

### 1. RFM and Lifecycle
- Recency
- Frequency
- Monetary value
- Customer tenure

### 2. Purchase Behavior
- Total items purchased
- Average items per order
- Average order value

### 3. Product and Seller Diversity
- Product diversity
- Category diversity
- Seller diversity

### 4. Freight Behavior
- Total freight expenditure
- Average freight per order
- Freight-to-merchandise ratio

### 5. Payment Behavior
- Total payment value
- Average payment value
- Payment method diversity
- Installment behavior

### 6. Satisfaction Behavior
- Average review score
- Review coverage

Features will be validated for missingness, skewness, redundancy, scale,
and business meaning before modeling.

In [ ]:
Step 5 — Build Core Customer Features
Now create the first customer-level table.

5A — Define reference date
The final delivered purchase occurred on:

In [13]:
reference_date = (
    order_analytics["order_purchase_timestamp"]
    .max()
    .normalize()
    + pd.Timedelta(days=1)
)

print("Reference date:", reference_date)

Reference date: 2018-08-30 00:00:00

In [ ]:
# Aggregate core features

In [15]:
customer_features = (
    order_analytics
    .groupby("customer_unique_id")
    .agg(
        first_purchase_date=(
            "order_purchase_timestamp", "min"
        ),

        last_purchase_date=(
            "order_purchase_timestamp", "max"
        ),

        frequency=(
            "order_id", "nunique"
        ),

        monetary_value=(
            "merchandise_value", "sum"
        ),

        total_order_value=(
            "order_value", "sum"
        ),

        avg_order_value=(
            "order_value", "mean"
        ),

        total_items=(
            "item_count", "sum"
        ),

        avg_items_per_order=(
            "item_count", "mean"
        )
    )
    .reset_index()
)

In [16]:
# Recency and tenure

customer_features["recency_days"] = (
    reference_date
    - customer_features["last_purchase_date"]
).dt.days

customer_features["tenure_days"] = (
    reference_date
    - customer_features["first_purchase_date"]
).dt.days

In [17]:
customer_features.head()

,customer_unique_id,first_purchase_date,last_purchase_date,frequency,monetary_value,total_order_value,avg_order_value,total_items,avg_items_per_order,recency_days,tenure_days
0,0000366f3b9a7992bf8c76cfdf3221e2,2018-05-10 10:56:27,2018-05-10 10:56:27,1,129.90,141.90,141.90,1,1.00,111,111
1,0000b849f77a49e4a4ce2b2a4ca5be3f,2018-05-07 11:11:27,2018-05-07 11:11:27,1,18.90,27.19,27.19,1,1.00,114,114
2,0000f46a3911fa3c0805444483337064,2017-03-10 21:05:03,2017-03-10 21:05:03,1,69.00,86.22,86.22,1,1.00,537,537
3,0000f6ccb0745a6a4b88665a16c9f078,2017-10-12 20:29:41,2017-10-12 20:29:41,1,25.99,43.62,43.62,1,1.00,321,321
4,0004aac84e0df4da2b147fca70cf8255,2017-11-14 19:45:42,2017-11-14 19:45:42,1,180.00,196.89,196.89,1,1.00,288,288

Validate customer grain

In [18]:
core_feature_validation = pd.Series({
    "rows":
        len(customer_features),

    "unique_customers":
        customer_features["customer_unique_id"].nunique(),

    "duplicate_customer_ids":
        customer_features["customer_unique_id"].duplicated().sum(),

    "missing_customer_ids":
        customer_features["customer_unique_id"].isna().sum(),

    "min_frequency":
        customer_features["frequency"].min(),

    "max_frequency":
        customer_features["frequency"].max(),

    "negative_recency":
        (customer_features["recency_days"] < 0).sum(),

    "negative_tenure":
        (customer_features["tenure_days"] < 0).sum(),

    "negative_monetary":
        (customer_features["monetary_value"] < 0).sum()
})

core_feature_validation

rows                      93358
unique_customers          93358
duplicate_customer_ids        0
missing_customer_ids          0
min_frequency                 1
max_frequency                15
negative_recency              0
negative_tenure               0
negative_monetary             0
dtype: int64

Step 6: Purchase Intensity, Freight & Repeat Behavior
6A — Add purchase-span and repeat behavior

There is an important distinction:

tenure_days = reference date − first purchase
purchase_span_days = last purchase − first purchase

The second measures the observed duration of actual purchasing activity.

In [20]:
customer_features["purchase_span_days"] = (
    customer_features["last_purchase_date"]
    - customer_features["first_purchase_date"]
).dt.days

customer_features["is_repeat_customer"] = (
    customer_features["frequency"] > 1
).astype(int)

In [21]:
# Now inspect repeat-customer prevalence:

repeat_summary = pd.Series({
    "total_customers":
        len(customer_features),

    "one_time_customers":
        (customer_features["frequency"] == 1).sum(),

    "repeat_customers":
        (customer_features["frequency"] > 1).sum(),

    "repeat_customer_pct":
        (customer_features["frequency"] > 1).mean() * 100
})

repeat_summary

total_customers       93,358.00
one_time_customers    90,557.00
repeat_customers       2,801.00
repeat_customer_pct        3.00
dtype: float64

This matters because if most customers purchased only once, features such as purchase span
and frequency will be heavily concentrated.

Aggregate freight behavior
Now derive freight features directly from order-level data:

In [22]:
customer_freight = (
    order_analytics
    .groupby("customer_unique_id")
    .agg(
        total_freight=(
            "freight_value", "sum"
        ),

        avg_freight_per_order=(
            "freight_value", "mean"
        ),

        avg_merchandise_per_order=(
            "merchandise_value", "mean"
        )
    )
    .reset_index()
)

customer_freight.head()

,customer_unique_id,total_freight,avg_freight_per_order,avg_merchandise_per_order
0,0000366f3b9a7992bf8c76cfdf3221e2,12.00,12.00,129.90
1,0000b849f77a49e4a4ce2b2a4ca5be3f,8.29,8.29,18.90
2,0000f46a3911fa3c0805444483337064,17.22,17.22,69.00
3,0000f6ccb0745a6a4b88665a16c9f078,17.63,17.63,25.99
4,0004aac84e0df4da2b147fca70cf8255,16.89,16.89,180.00

In [23]:
# Freight-to-merchandise ratio
# Do not average order-level freight percentages. Calculate the ratio from customer-level totals.

customer_freight["freight_to_merchandise_ratio"] = (
    customer_freight["total_freight"]
    /
    customer_features.set_index("customer_unique_id")
    .loc[
        customer_freight["customer_unique_id"],
        "monetary_value"
    ]
    .to_numpy()
)

In [24]:
freight_validation = pd.Series({
    "rows":
        len(customer_freight),

    "unique_customers":
        customer_freight["customer_unique_id"].nunique(),

    "missing_total_freight":
        customer_freight["total_freight"].isna().sum(),

    "negative_total_freight":
        (customer_freight["total_freight"] < 0).sum(),

    "missing_ratio":
        customer_freight["freight_to_merchandise_ratio"].isna().sum(),

    "infinite_ratio":
        np.isinf(
            customer_freight["freight_to_merchandise_ratio"]
        ).sum(),

    "max_ratio":
        customer_freight["freight_to_merchandise_ratio"].max()
})

freight_validation

rows                     93,358.00
unique_customers         93,358.00
missing_total_freight         0.00
negative_total_freight        0.00
missing_ratio                 0.00
infinite_ratio                0.00
max_ratio                    21.45
dtype: float64

In [26]:
# Join freight features


customer_features = (
    customer_features
    .merge(
        customer_freight[
            [
                "customer_unique_id",
                "total_freight",
                "avg_freight_per_order",
                "avg_merchandise_per_order",
                "freight_to_merchandise_ratio"
            ]
        ],
        on="customer_unique_id",
        how="left",
        validate="one_to_one"
    )
)

In [27]:
# Validate the grain again:

pd.Series({
    "rows": len(customer_features),

    "unique_customers":
        customer_features["customer_unique_id"].nunique(),

    "duplicate_customer_ids":
        customer_features["customer_unique_id"].duplicated().sum()
})

rows                      93358
unique_customers          93358
duplicate_customer_ids        0
dtype: int64

Only 2,801 of 93,358 customers are repeat customers — about 3%. Roughly 97% are one-time customers.

That means Frequency will be extremely concentrated at 1. This is important later: a basic RFM + K-Means
model may be dominated by Recency and Monetary because Frequency has limited variation. We should not manufacture
more repeat behavior; the model must reflect the dataset.

The freight validation also passes: no missing, negative, or infinite ratios. But max_ratio = 21.45 is
extreme — one customer's freight was more than 21× merchandise spending. We won't delete it now.
Phase 4 will investigate its distribution and determine whether transformations
such as log1p or robust scaling are appropriate.

In [ ]:
# Payment Behavior
Payments can capture behavior beyond spending: payment-method usage and installment behavior.
Aggregate payment features

In [28]:
customer_payment = (
    order_analytics
    .groupby("customer_unique_id")
    .agg(
        total_payment_value=(
            "payment_value", "sum"
        ),

        avg_payment_value=(
            "payment_value", "mean"
        ),

        avg_payment_records_per_order=(
            "payment_record_count", "mean"
        ),

        max_payment_methods_per_order=(
            "payment_method_count", "max"
        ),

        avg_payment_methods_per_order=(
            "payment_method_count", "mean"
        ),

        max_installments=(
            "max_installments", "max"
        ),

        avg_installments=(
            "avg_installments", "mean"
        )
    )
    .reset_index()
)

customer_payment.head()

,customer_unique_id,total_payment_value,avg_payment_value,avg_payment_records_per_order,max_payment_methods_per_order,avg_payment_methods_per_order,max_installments,avg_installments
0,0000366f3b9a7992bf8c76cfdf3221e2,141.90,141.90,1.00,1.00,1.00,8.00,8.00
1,0000b849f77a49e4a4ce2b2a4ca5be3f,27.19,27.19,1.00,1.00,1.00,1.00,1.00
2,0000f46a3911fa3c0805444483337064,86.22,86.22,1.00,1.00,1.00,8.00,8.00
3,0000f6ccb0745a6a4b88665a16c9f078,43.62,43.62,1.00,1.00,1.00,4.00,4.00
4,0004aac84e0df4da2b147fca70cf8255,196.89,196.89,1.00,1.00,1.00,6.00,6.00

Remember: payment_method_count here is per-order diversity, so its customer-level maximum/average
is not the same as the number of distinct payment methods used across the customer's entire history.

In [29]:
# Validate payment features

payment_validation = pd.Series({
    "rows":
        len(customer_payment),

    "unique_customers":
        customer_payment["customer_unique_id"].nunique(),

    "missing_total_payment":
        customer_payment["total_payment_value"].isna().sum(),

    "missing_avg_payment":
        customer_payment["avg_payment_value"].isna().sum(),

    "missing_avg_payment_records":
        customer_payment[
            "avg_payment_records_per_order"
        ].isna().sum(),

    "missing_max_installments":
        customer_payment["max_installments"].isna().sum(),

    "negative_total_payment":
        (customer_payment["total_payment_value"] < 0).sum()
})

payment_validation

rows                           93358
unique_customers               93358
missing_total_payment              0
missing_avg_payment                1
missing_avg_payment_records        1
missing_max_installments           1
negative_total_payment             0
dtype: int64

We know one delivered order lacks payment information, but that does not necessarily mean one customer
will have missing customer-level payment features. A repeat customer could have another order with valid payment data.

In [31]:
# Join to customer table

customer_features = (
    customer_features
    .merge(
        customer_payment,
        on="customer_unique_id",
        how="left",
        validate="one_to_one"
    )
)

In [32]:
pd.Series({
    "rows":
        len(customer_features),

    "unique_customers":
        customer_features["customer_unique_id"].nunique(),

    "duplicate_customer_ids":
        customer_features["customer_unique_id"]
        .duplicated()
        .sum()
})

rows                      93358
unique_customers          93358
duplicate_customer_ids        0
dtype: int64

Satisfaction Behavior
We have 646 orders without reviews. At customer level, we need to distinguish review score from review availability.

In [34]:
# Aggregate satisfaction


customer_review = (
    order_analytics
    .groupby("customer_unique_id")
    .agg(
        avg_review_score=(
            "avg_review_score", "mean"
        ),

        reviewed_orders=(
            "avg_review_score", "count"
        ),

        total_orders_for_review=(
            "order_id", "nunique"
        )
    )
    .reset_index()
)

customer_review["review_coverage_ratio"] = (
    customer_review["reviewed_orders"]
    / customer_review["total_orders_for_review"]
)

customer_review.head()

,customer_unique_id,avg_review_score,reviewed_orders,total_orders_for_review,review_coverage_ratio
0,0000366f3b9a7992bf8c76cfdf3221e2,5.00,1,1,1.00
1,0000b849f77a49e4a4ce2b2a4ca5be3f,4.00,1,1,1.00
2,0000f46a3911fa3c0805444483337064,3.00,1,1,1.00
3,0000f6ccb0745a6a4b88665a16c9f078,4.00,1,1,1.00
4,0004aac84e0df4da2b147fca70cf8255,5.00,1,1,1.00

Customer A:
5 orders
4 reviewed

review_coverage_ratio = 4 / 5 = 0.80
This preserves two different signals:

Satisfaction: What scores did they give?

Coverage: How much of their purchasing history has review information?

Validate

In [35]:
review_validation = pd.Series({
    "rows":
        len(customer_review),

    "unique_customers":
        customer_review["customer_unique_id"].nunique(),

    "customers_without_review":
        customer_review["avg_review_score"].isna().sum(),

    "min_review_score":
        customer_review["avg_review_score"].min(),

    "max_review_score":
        customer_review["avg_review_score"].max(),

    "min_review_coverage":
        customer_review["review_coverage_ratio"].min(),

    "max_review_coverage":
        customer_review["review_coverage_ratio"].max()
})

review_validation

rows                       93,358.00
unique_customers           93,358.00
customers_without_review      603.00
min_review_score                1.00
max_review_score                5.00
min_review_coverage             0.00
max_review_coverage             1.00
dtype: float64

In [36]:
# Fix payment missingness semantics

no_payment_mask = (
    customer_payment["avg_payment_value"].isna()
)

customer_payment.loc[
    no_payment_mask,
    "total_payment_value"
] = np.nan

In [37]:
customer_payment.loc[
    customer_payment["avg_payment_value"].isna()
]

,customer_unique_id,total_payment_value,avg_payment_value,avg_payment_records_per_order,max_payment_methods_per_order,avg_payment_methods_per_order,max_installments,avg_installments
47882,830d5b7aaa3b6f1e9ad63703bec97d23,NaN,NaN,NaN,NaN,NaN,NaN,NaN

Refresh the joined table
We already joined the old customer_payment into customer_features, so correcting customer_payment
alone does not update customer_features.

In [38]:
payment_feature_cols = [
    "total_payment_value",
    "avg_payment_value",
    "avg_payment_records_per_order",
    "max_payment_methods_per_order",
    "avg_payment_methods_per_order",
    "max_installments",
    "avg_installments"
]

customer_features = customer_features.drop(
    columns=payment_feature_cols
)

customer_features = (
    customer_features
    .merge(
        customer_payment,
        on="customer_unique_id",
        how="left",
        validate="one_to_one"
    )
)

In [39]:
customer_features[
    customer_features["avg_payment_value"].isna()
][
    [
        "customer_unique_id",
        "total_payment_value",
        "avg_payment_value",
        "max_installments"
    ]
]

,customer_unique_id,total_payment_value,avg_payment_value,max_installments
47882,830d5b7aaa3b6f1e9ad63703bec97d23,NaN,NaN,NaN

Join review features
Add the validated review table:

In [40]:
customer_features = (
    customer_features
    .merge(
        customer_review[
            [
                "customer_unique_id",
                "avg_review_score",
                "reviewed_orders",
                "review_coverage_ratio"
            ]
        ],
        on="customer_unique_id",
        how="left",
        validate="one_to_one"
    )
)

In [41]:
# Validate the customer grain:

pd.Series({
    "rows":
        len(customer_features),

    "unique_customers":
        customer_features["customer_unique_id"].nunique(),

    "duplicate_customer_ids":
        customer_features["customer_unique_id"]
        .duplicated()
        .sum(),

    "customers_missing_payment":
        customer_features["avg_payment_value"].isna().sum(),

    "customers_missing_review":
        customer_features["avg_review_score"].isna().sum()
})

rows                         93358
unique_customers             93358
duplicate_customer_ids           0
customers_missing_payment        1
customers_missing_review       603
dtype: int64

Exact Product, Category & Seller Diversity
Here we should not use the order-level product_count, category_count, and seller_count to
claim customer-level unique diversity.

We need to return to the item-level source data.

unique_products
unique_categories
unique_sellers

customer_unique_id
        ↑
      orders
        ↓
    order_items
      ↙     ↘
 product   seller
   ↓
category

This will give us actual cross-order diversity.

Before constructing it, we need to load the required raw tables into the Phase 3 notebook.

In [42]:
customers_raw = pd.read_csv(
    DATA_RAW / "olist_customers_dataset.csv"
)

order_items_raw = pd.read_csv(
    DATA_RAW / "olist_order_items_dataset.csv"
)

products_raw = pd.read_csv(
    DATA_RAW / "olist_products_dataset.csv"
)

print("Customers:", customers_raw.shape)
print("Order items:", order_items_raw.shape)
print("Products:", products_raw.shape)

Customers: (99441, 5)
Order items: (112650, 7)
Products: (32951, 9)

Then validate the keys we will depend on:

In [43]:
diversity_source_validation = pd.Series({
    "duplicate_customer_ids":
        customers_raw["customer_id"].duplicated().sum(),

    "duplicate_product_ids":
        products_raw["product_id"].duplicated().sum(),

    "missing_customer_unique_id":
        customers_raw["customer_unique_id"].isna().sum(),

    "missing_item_order_id":
        order_items_raw["order_id"].isna().sum(),

    "missing_item_product_id":
        order_items_raw["product_id"].isna().sum(),

    "missing_item_seller_id":
        order_items_raw["seller_id"].isna().sum()
})

diversity_source_validation

duplicate_customer_ids        0
duplicate_product_ids         0
missing_customer_unique_id    0
missing_item_order_id         0
missing_item_product_id       0
missing_item_seller_id        0
dtype: int64

Both validations pass.

We now have a stable customer table of 93,358 customers, with only 1 customer missing payment
information and 603 customers with no review score. The source tables required for exact diversity
features also have clean keys and no missing relationship IDs.

Exact Customer Diversity Features
This is important because we want true customer-level diversity, not the sum of order-level unique counts.

Build the delivered item/customer bridge
We already know which orders are valid from order_analytics, so use that as our delivered-order population.

In [45]:
# Now connect those orders to their items:

customer_items = (
    delivered_order_customer
    .merge(
        order_items_raw[
            [
                "order_id",
                "product_id",
                "seller_id"
            ]
        ],
        on="order_id",
        how="left",
        validate="one_to_many"
    )
)

print("Rows:", len(customer_items))
print(
    "Unique orders:",
    customer_items["order_id"].nunique()
)

print(
    "Unique customers:",
    customer_items["customer_unique_id"].nunique()
)

Rows: 110197
Unique orders: 96478
Unique customers: 93358

In [46]:
# Add product category

customer_items = (
    customer_items
    .merge(
        products_raw[
            [
                "product_id",
                "product_category_name"
            ]
        ],
        on="product_id",
        how="left",
        validate="many_to_one"
    )
)

In [47]:
item_bridge_validation = pd.Series({
    "rows":
        len(customer_items),

    "unique_orders":
        customer_items["order_id"].nunique(),

    "unique_customers":
        customer_items["customer_unique_id"].nunique(),

    "missing_product_id":
        customer_items["product_id"].isna().sum(),

    "missing_seller_id":
        customer_items["seller_id"].isna().sum(),

    "missing_category":
        customer_items["product_category_name"].isna().sum()
})

item_bridge_validation

rows                  110197
unique_orders          96478
unique_customers       93358
missing_product_id         0
missing_seller_id          0
missing_category        1537
dtype: int64

category missingness is expected. Product and seller IDs should not be missing.

In [ ]:
# Calculate True Diversity
# Customer-level unique counts

In [48]:
customer_diversity = (
    customer_items
    .groupby("customer_unique_id")
    .agg(
        unique_products=(
            "product_id", "nunique"
        ),

        unique_categories=(
            "product_category_name", "nunique"
        ),

        unique_sellers=(
            "seller_id", "nunique"
        )
    )
    .reset_index()
)

customer_diversity.head()

,customer_unique_id,unique_products,unique_categories,unique_sellers
0,0000366f3b9a7992bf8c76cfdf3221e2,1,1,1
1,0000b849f77a49e4a4ce2b2a4ca5be3f,1,1,1
2,0000f46a3911fa3c0805444483337064,1,1,1
3,0000f6ccb0745a6a4b88665a16c9f078,1,1,1
4,0004aac84e0df4da2b147fca70cf8255,1,1,1

Add category availability
Because nunique() ignores missing categories, a customer purchasing only products with missing category metadata could get:

That does not mean the customer purchased zero categories.

In [53]:
category_availability = (
    customer_items
    .groupby("customer_unique_id")
    ["product_category_name"]
    .apply(lambda x: x.notna().mean())
    .rename("category_data_coverage")
    .reset_index()
)

customer_diversity = (
    customer_diversity
    .merge(
        category_availability,
        on="customer_unique_id",
        how="left",
        validate="one_to_one"
    )
)

In [54]:
diversity_validation = pd.Series({
    "rows":
        len(customer_diversity),

    "unique_customers":
        customer_diversity["customer_unique_id"].nunique(),

    "duplicate_customer_ids":
        customer_diversity["customer_unique_id"]
        .duplicated()
        .sum(),

    "min_unique_products":
        customer_diversity["unique_products"].min(),

    "max_unique_products":
        customer_diversity["unique_products"].max(),

    "min_unique_categories":
        customer_diversity["unique_categories"].min(),

    "max_unique_categories":
        customer_diversity["unique_categories"].max(),

    "min_unique_sellers":
        customer_diversity["unique_sellers"].min(),

    "max_unique_sellers":
        customer_diversity["unique_sellers"].max(),

    "min_category_coverage":
        customer_diversity["category_data_coverage"].min(),

    "max_category_coverage":
        customer_diversity["category_data_coverage"].max()
})

diversity_validation

rows                     93,358.00
unique_customers         93,358.00
duplicate_customer_ids        0.00
min_unique_products           1.00
max_unique_products          14.00
min_unique_categories         0.00
max_unique_categories         5.00
min_unique_sellers            1.00
max_unique_sellers           10.00
min_category_coverage         0.00
max_category_coverage         1.00
dtype: float64

In [ ]:
Join to the master customer table

In [55]:
# Join to the master customer table

customer_features = (
    customer_features
    .merge(
        customer_diversity,
        on="customer_unique_id",
        how="left",
        validate="one_to_one"
    )
)

In [56]:
pd.Series({
    "rows":
        len(customer_features),

    "unique_customers":
        customer_features["customer_unique_id"].nunique(),

    "duplicate_customer_ids":
        customer_features["customer_unique_id"]
        .duplicated()
        .sum(),

    "missing_diversity":
        customer_features["unique_products"].isna().sum()
})

rows                      93358
unique_customers          93358
duplicate_customer_ids        0
missing_diversity             0
dtype: int64

Purchasing Intensity

We already know approximately 97% of customers purchased only once. That makes some common behavioral features dangerous.

For example:

orders_per_month = frequency / purchase_span
For a one-time customer:

first_purchase = last_purchase
purchase_span_days = 0
So we'd create division-by-zero or meaningless artificial intensity.

We should explicitly separate repeat-customer behavior.

Analyze purchase span

In [57]:
span_summary = pd.Series({
    "zero_purchase_span":
        (customer_features["purchase_span_days"] == 0).sum(),

    "positive_purchase_span":
        (customer_features["purchase_span_days"] > 0).sum(),

    "min_purchase_span":
        customer_features["purchase_span_days"].min(),

    "max_purchase_span":
        customer_features["purchase_span_days"].max()
})

span_summary

zero_purchase_span        91365
positive_purchase_span     1993
min_purchase_span             0
max_purchase_span           633
dtype: int64

In [58]:
pd.crosstab(
    customer_features["frequency"] > 1,
    customer_features["purchase_span_days"] == 0,
    rownames=["repeat_customer"],
    colnames=["zero_purchase_span"]
)

zero_purchase_span  False  True
repeat_customer
False                   0  90557
True                 1993    808

This checks whether any repeat customer placed multiple orders on the same calendar day.

11B — Average days between purchases

This feature only has a meaningful definition for repeat customers.

For n purchases, there are n - 1 intervals:

In [59]:
customer_features["avg_days_between_purchases"] = np.where(
    customer_features["frequency"] > 1,

    customer_features["purchase_span_days"]
    / (customer_features["frequency"] - 1),

    np.nan
)

In [60]:
interval_validation = pd.Series({
    "customers_with_interval":
        customer_features[
            "avg_days_between_purchases"
        ].notna().sum(),

    "customers_without_interval":
        customer_features[
            "avg_days_between_purchases"
        ].isna().sum(),

    "negative_intervals":
        (
            customer_features["avg_days_between_purchases"] < 0
        ).sum(),

    "min_interval":
        customer_features["avg_days_between_purchases"].min(),

    "max_interval":
        customer_features["avg_days_between_purchases"].max()
})

interval_validation

customers_with_interval       2,801.00
customers_without_interval   90,557.00
negative_intervals                0.00
min_interval                      0.00
max_interval                    608.00
dtype: float64

In [62]:
# Item/Product Intensity
# Now derive interpretable ratios from our exact diversity features.

# First confirm that Step 10D was executed and unique_products exists:

print(
    "unique_products" in customer_features.columns,
    "unique_categories" in customer_features.columns,
    "unique_sellers" in customer_features.columns
)

True True True

In [63]:
customer_features["items_per_product"] = (
    customer_features["total_items"]
    / customer_features["unique_products"]
)

customer_features["products_per_order"] = (
    customer_features["unique_products"]
    / customer_features["frequency"]
)

customer_features["sellers_per_order"] = (
    customer_features["unique_sellers"]
    / customer_features["frequency"]
)

These describe different behavior.

items_per_product > 1 can indicate repeated quantities or repeated purchasing of the same product.

products_per_order approximates cross-history product diversity relative to ordering frequency.

sellers_per_order measures seller diversity relative to number of orders.

In [64]:
intensity_validation = pd.Series({
    "missing_items_per_product":
        customer_features["items_per_product"].isna().sum(),

    "missing_products_per_order":
        customer_features["products_per_order"].isna().sum(),

    "missing_sellers_per_order":
        customer_features["sellers_per_order"].isna().sum(),

    "infinite_items_per_product":
        np.isinf(customer_features["items_per_product"]).sum(),

    "min_items_per_product":
        customer_features["items_per_product"].min(),

    "max_items_per_product":
        customer_features["items_per_product"].max(),

    "min_products_per_order":
        customer_features["products_per_order"].min(),

    "max_products_per_order":
        customer_features["products_per_order"].max()
})

intensity_validation

missing_items_per_product     0.00
missing_products_per_order    0.00
missing_sellers_per_order     0.00
infinite_items_per_product    0.00
min_items_per_product         1.00
max_items_per_product        24.00
min_products_per_order        0.25
max_products_per_order        8.00
dtype: float64

In [65]:
# Final Feature Audit

print("Shape:", customer_features.shape)

print("\nColumns:")
for i, col in enumerate(customer_features.columns, start=1):
    print(f"{i:02d}. {col}")

Shape: (93358, 41)

Columns:
01. customer_unique_id
02. first_purchase_date
03. last_purchase_date
04. frequency
05. monetary_value
06. total_order_value
07. avg_order_value
08. total_items
09. avg_items_per_order
10. recency_days
11. tenure_days
12. purchase_span_days
13. is_repeat_customer
14. total_freight_x
15. avg_freight_per_order_x
16. avg_merchandise_per_order_x
17. freight_to_merchandise_ratio_x
18. total_freight_y
19. avg_freight_per_order_y
20. avg_merchandise_per_order_y
21. freight_to_merchandise_ratio_y
22. total_payment_value
23. avg_payment_value
24. avg_payment_records_per_order
25. max_payment_methods_per_order
26. avg_payment_methods_per_order
27. max_installments
28. avg_installments
29. avg_review_score
30. reviewed_orders
31. review_coverage_ratio
32. unique_products
33. unique_categories
34. unique_sellers
35. category_data_coverage_x
36. category_data_coverage_y
37. category_data_coverage
38. avg_days_between_purchases
39. items_per_product
40. products_per_order
41. sellers_per_order

In [66]:
customer_features.head()

,customer_unique_id,first_purchase_date,last_purchase_date,frequency,monetary_value,total_order_value,avg_order_value,total_items,avg_items_per_order,recency_days,tenure_days,purchase_span_days,is_repeat_customer,total_freight_x,avg_freight_per_order_x,avg_merchandise_per_order_x,freight_to_merchandise_ratio_x,total_freight_y,avg_freight_per_order_y,avg_merchandise_per_order_y,freight_to_merchandise_ratio_y,total_payment_value,avg_payment_value,avg_payment_records_per_order,max_payment_methods_per_order,avg_payment_methods_per_order,max_installments,avg_installments,avg_review_score,reviewed_orders,review_coverage_ratio,unique_products,unique_categories,unique_sellers,category_data_coverage_x,category_data_coverage_y,category_data_coverage,avg_days_between_purchases,items_per_product,products_per_order,sellers_per_order
0,0000366f3b9a7992bf8c76cfdf3221e2,2018-05-10 10:56:27,2018-05-10 10:56:27,1,129.90,141.90,141.90,1,1.00,111,111,0,0,12.00,12.00,129.90,0.09,12.00,12.00,129.90,0.09,141.90,141.90,1.00,1.00,1.00,8.00,8.00,5.00,1,1.00,1,1,1,1.00,1.00,1.00,NaN,1.00,1.00,1.00
1,0000b849f77a49e4a4ce2b2a4ca5be3f,2018-05-07 11:11:27,2018-05-07 11:11:27,1,18.90,27.19,27.19,1,1.00,114,114,0,0,8.29,8.29,18.90,0.44,8.29,8.29,18.90,0.44,27.19,27.19,1.00,1.00,1.00,1.00,1.00,4.00,1,1.00,1,1,1,1.00,1.00,1.00,NaN,1.00,1.00,1.00
2,0000f46a3911fa3c0805444483337064,2017-03-10 21:05:03,2017-03-10 21:05:03,1,69.00,86.22,86.22,1,1.00,537,537,0,0,17.22,17.22,69.00,0.25,17.22,17.22,69.00,0.25,86.22,86.22,1.00,1.00,1.00,8.00,8.00,3.00,1,1.00,1,1,1,1.00,1.00,1.00,NaN,1.00,1.00,1.00
3,0000f6ccb0745a6a4b88665a16c9f078,2017-10-12 20:29:41,2017-10-12 20:29:41,1,25.99,43.62,43.62,1,1.00,321,321,0,0,17.63,17.63,25.99,0.68,17.63,17.63,25.99,0.68,43.62,43.62,1.00,1.00,1.00,4.00,4.00,4.00,1,1.00,1,1,1,1.00,1.00,1.00,NaN,1.00,1.00,1.00
4,0004aac84e0df4da2b147fca70cf8255,2017-11-14 19:45:42,2017-11-14 19:45:42,1,180.00,196.89,196.89,1,1.00,288,288,0,0,16.89,16.89,180.00,0.09,16.89,16.89,180.00,0.09,196.89,196.89,1.00,1.00,1.00,6.00,6.00,5.00,1,1.00,1,1,1,1.00,1.00,1.00,NaN,1.00,1.00,1.00

In [67]:
# Missingness audit

missing_audit = (
    customer_features
    .isna()
    .sum()
    .to_frame("missing_count")
)

missing_audit["missing_pct"] = (
    missing_audit["missing_count"]
    / len(customer_features)
    * 100
)

missing_audit = (
    missing_audit[
        missing_audit["missing_count"] > 0
    ]
    .sort_values(
        "missing_pct",
        ascending=False
    )
)

missing_audit

                               missing_count  missing_pct
avg_days_between_purchases             90557        97.00
avg_review_score                         603         0.65
total_payment_value                        1         0.00
avg_payment_value                          1         0.00
avg_payment_records_per_order              1         0.00
max_payment_methods_per_order              1         0.00
avg_payment_methods_per_order              1         0.00
max_installments                           1         0.00
avg_installments                           1         0.00

We already expect heavy missingness for avg_days_between_purchases, plus 603 missing review scores
and 1 missing payment customer.

In [69]:
# Constant and near-constant numerical features
# First identify numeric columns:

numeric_cols = customer_features.select_dtypes(
    include=np.number
).columns.tolist()

print("Numeric features:", len(numeric_cols))

Numeric features: 38

In [70]:
feature_variation = []

for col in numeric_cols:
    counts = customer_features[col].value_counts(
        normalize=True,
        dropna=False
    )

    feature_variation.append({
        "feature": col,
        "unique_values":
            customer_features[col].nunique(dropna=False),

        "most_common_pct":
            counts.iloc[0] * 100
    })

feature_variation = (
    pd.DataFrame(feature_variation)
    .sort_values(
        "most_common_pct",
        ascending=False
    )
)

feature_variation

                           feature  unique_values  most_common_pct
27           review_coverage_ratio              5            99.32
33          category_data_coverage             16            98.52
32        category_data_coverage_y             16            98.52
31        category_data_coverage_x             16            98.52
8               purchase_span_days            414            97.87
37               sellers_per_order             23            97.79
21   max_payment_methods_per_order              3            97.69
22   avg_payment_methods_per_order              8            97.69
34      avg_days_between_purchases            499            97.00
0                        frequency              9            97.00
9               is_repeat_customer              2            97.00
20   avg_payment_records_per_order             32            96.97
30                  unique_sellers              8            96.59
26                 reviewed_orders             10            96.39
29               unique_categories              6            96.34
36              products_per_order             28            96.26
28                 unique_products             11            94.29
35               items_per_product             41            92.45
5              avg_items_per_order             39            89.84
4                      total_items             19            87.56
25                avg_review_score             35            58.32
24                avg_installments             92            48.36
23                max_installments             25            48.36
15         avg_freight_per_order_y           8985             2.91
11         avg_freight_per_order_x           8985             2.91
10                 total_freight_x           8501             2.88
14                 total_freight_y           8501             2.88
16     avg_merchandise_per_order_y           8812             1.71
12     avg_merchandise_per_order_x           8812             1.71
1                   monetary_value           8459             1.70
7                      tenure_days            612             1.19
6                     recency_days            611             1.19
17  freight_to_merchandise_ratio_y          44263             0.35
13  freight_to_merchandise_ratio_x          44263             0.35
3                  avg_order_value          31354             0.26
2                total_order_value          31206             0.26
18             total_payment_value          28261             0.25
19               avg_payment_value          28432             0.25

In [ ]:
This is important because a feature can technically vary while carrying almost no useful information.

In [71]:
# Basic integrity audit

integrity_audit = pd.Series({
    "rows":
        len(customer_features),

    "unique_customers":
        customer_features["customer_unique_id"].nunique(),

    "duplicate_customer_ids":
        customer_features["customer_unique_id"]
        .duplicated()
        .sum(),

    "negative_recency":
        (customer_features["recency_days"] < 0).sum(),

    "negative_tenure":
        (customer_features["tenure_days"] < 0).sum(),

    "negative_frequency":
        (customer_features["frequency"] < 0).sum(),

    "negative_monetary":
        (customer_features["monetary_value"] < 0).sum(),

    "infinite_numeric_values":
        np.isinf(
            customer_features[numeric_cols]
        ).sum().sum()
})

integrity_audit

rows                       93358
unique_customers           93358
duplicate_customer_ids         0
negative_recency               0
negative_tenure                0
negative_frequency             0
negative_monetary              0
infinite_numeric_values        0
dtype: int64

Rebuild core features

In [72]:
customer_features_clean = (
    order_analytics
    .groupby("customer_unique_id")
    .agg(
        first_purchase_date=(
            "order_purchase_timestamp", "min"
        ),
        last_purchase_date=(
            "order_purchase_timestamp", "max"
        ),
        frequency=(
            "order_id", "nunique"
        ),
        monetary_value=(
            "merchandise_value", "sum"
        ),
        total_order_value=(
            "order_value", "sum"
        ),
        avg_order_value=(
            "order_value", "mean"
        ),
        total_items=(
            "item_count", "sum"
        ),
        avg_items_per_order=(
            "item_count", "mean"
        )
    )
    .reset_index()
)

In [73]:
# Recreate lifecycle features

customer_features_clean["recency_days"] = (
    reference_date
    - customer_features_clean["last_purchase_date"]
).dt.days

customer_features_clean["tenure_days"] = (
    reference_date
    - customer_features_clean["first_purchase_date"]
).dt.days

customer_features_clean["purchase_span_days"] = (
    customer_features_clean["last_purchase_date"]
    - customer_features_clean["first_purchase_date"]
).dt.days

customer_features_clean["is_repeat_customer"] = (
    customer_features_clean["frequency"] > 1
).astype(int)

In [74]:
# Merge validated feature families once

customer_features_clean = (
    customer_features_clean

    .merge(
        customer_freight,
        on="customer_unique_id",
        how="left",
        validate="one_to_one"
    )

    .merge(
        customer_payment,
        on="customer_unique_id",
        how="left",
        validate="one_to_one"
    )

    .merge(
        customer_review[
            [
                "customer_unique_id",
                "avg_review_score",
                "reviewed_orders",
                "review_coverage_ratio"
            ]
        ],
        on="customer_unique_id",
        how="left",
        validate="one_to_one"
    )

    .merge(
        customer_diversity,
        on="customer_unique_id",
        how="left",
        validate="one_to_one"
    )
)

In [75]:
# Recreate intensity features

customer_features_clean["avg_days_between_purchases"] = np.where(
    customer_features_clean["frequency"] > 1,
    customer_features_clean["purchase_span_days"]
    / (customer_features_clean["frequency"] - 1),
    np.nan
)

customer_features_clean["items_per_product"] = (
    customer_features_clean["total_items"]
    / customer_features_clean["unique_products"]
)

customer_features_clean["products_per_order"] = (
    customer_features_clean["unique_products"]
    / customer_features_clean["frequency"]
)

customer_features_clean["sellers_per_order"] = (
    customer_features_clean["unique_sellers"]
    / customer_features_clean["frequency"]
)

In [76]:
# Check for contamination

duplicate_suffix_cols = [
    col for col in customer_features_clean.columns
    if col.endswith("_x") or col.endswith("_y")
]

print("Shape:", customer_features_clean.shape)
print("Duplicate suffix columns:", duplicate_suffix_cols)

Shape: (93358, 37)
Duplicate suffix columns: ['category_data_coverage_x', 'category_data_coverage_y']

In [77]:
pd.Series({
    "rows":
        len(customer_features_clean),

    "unique_customers":
        customer_features_clean["customer_unique_id"].nunique(),

    "duplicate_customer_ids":
        customer_features_clean["customer_unique_id"]
        .duplicated()
        .sum(),

    "missing_payment":
        customer_features_clean["avg_payment_value"].isna().sum(),

    "missing_review":
        customer_features_clean["avg_review_score"].isna().sum(),

    "missing_diversity":
        customer_features_clean["unique_products"].isna().sum()
})

rows                      93358
unique_customers          93358
duplicate_customer_ids        0
missing_payment               1
missing_review              603
missing_diversity             0
dtype: int64

In [78]:
# Rebuild diversity table

customer_diversity_clean = (
    customer_items
    .groupby("customer_unique_id")
    .agg(
        unique_products=(
            "product_id", "nunique"
        ),

        unique_categories=(
            "product_category_name", "nunique"
        ),

        unique_sellers=(
            "seller_id", "nunique"
        ),

        category_data_coverage=(
            "product_category_name",
            lambda x: x.notna().mean()
        )
    )
    .reset_index()
)

In [79]:
print(customer_diversity_clean.columns.tolist())
print(customer_diversity_clean.shape)

['customer_unique_id', 'unique_products', 'unique_categories', 'unique_sellers', 'category_data_coverage']
(93358, 5)

Replace the contaminated diversity columns
Because customer_features_clean currently contains the bad diversity merge, remove all diversity-related columns first:

In [80]:
diversity_cols_to_remove = [
    col for col in customer_features_clean.columns
    if (
        col.startswith("unique_products")
        or col.startswith("unique_categories")
        or col.startswith("unique_sellers")
        or col.startswith("category_data_coverage")
    )
]

print(diversity_cols_to_remove)

customer_features_clean = (
    customer_features_clean
    .drop(columns=diversity_cols_to_remove)
)

['unique_products', 'unique_categories', 'unique_sellers', 'category_data_coverage_x', 'category_data_coverage_y', 'category_data_coverage']

In [81]:
customer_features_clean = (
    customer_features_clean
    .merge(
        customer_diversity_clean,
        on="customer_unique_id",
        how="left",
        validate="one_to_one"
    )
)

In [82]:
customer_features_clean["items_per_product"] = (
    customer_features_clean["total_items"]
    / customer_features_clean["unique_products"]
)

customer_features_clean["products_per_order"] = (
    customer_features_clean["unique_products"]
    / customer_features_clean["frequency"]
)

customer_features_clean["sellers_per_order"] = (
    customer_features_clean["unique_sellers"]
    / customer_features_clean["frequency"]
)

In [83]:
suffix_cols = [
    col for col in customer_features_clean.columns
    if col.endswith("_x") or col.endswith("_y")
]

pd.Series({
    "rows":
        len(customer_features_clean),

    "columns":
        len(customer_features_clean.columns),

    "unique_customers":
        customer_features_clean["customer_unique_id"].nunique(),

    "duplicate_customer_ids":
        customer_features_clean["customer_unique_id"]
        .duplicated()
        .sum(),

    "suffix_columns":
        len(suffix_cols),

    "missing_diversity":
        customer_features_clean["unique_products"].isna().sum()
})

rows                      93358
columns                      35
unique_customers          93358
duplicate_customer_ids        0
suffix_columns                0
missing_diversity             0
dtype: int64

In [84]:
print("Suffix columns:", suffix_cols)

Suffix columns: []

In [85]:
# Final Feature Classification
# We engineered many candidate variables, but we are not going to model with everything.

# First, inspect the clean table:

print("Shape:", customer_features_clean.shape)

for i, col in enumerate(customer_features_clean.columns, 1):
    print(f"{i:02d}. {col}")

Shape: (93358, 35)
01. customer_unique_id
02. first_purchase_date
03. last_purchase_date
04. frequency
05. monetary_value
06. total_order_value
07. avg_order_value
08. total_items
09. avg_items_per_order
10. recency_days
11. tenure_days
12. purchase_span_days
13. is_repeat_customer
14. total_freight
15. avg_freight_per_order
16. avg_merchandise_per_order
17. freight_to_merchandise_ratio
18. total_payment_value
19. avg_payment_value
20. avg_payment_records_per_order
21. max_payment_methods_per_order
22. avg_payment_methods_per_order
23. max_installments
24. avg_installments
25. avg_review_score
26. reviewed_orders
27. review_coverage_ratio
28. avg_days_between_purchases
29. items_per_product
30. products_per_order
31. sellers_per_order
32. unique_products
33. unique_categories
34. unique_sellers
35. category_data_coverage

In [86]:
# Classify the features
# For now, define four groups.

id_columns = [
    "customer_unique_id"
]

date_columns = [
    "first_purchase_date",
    "last_purchase_date"
]

profiling_only_features = [
    "is_repeat_customer",
    "purchase_span_days",
    "avg_days_between_purchases",
    "reviewed_orders",
    "category_data_coverage"
]

In [87]:
candidate_model_features = [
    # RFM / lifecycle
    "recency_days",
    "frequency",
    "monetary_value",
    "tenure_days",

    # Purchase behavior
    "total_items",
    "avg_items_per_order",
    "avg_order_value",

    # Freight behavior
    "avg_freight_per_order",
    "freight_to_merchandise_ratio",

    # Payment behavior
    "avg_payment_records_per_order",
    "max_installments",
    "avg_installments",

    # Satisfaction
    "avg_review_score",
    "review_coverage_ratio",

    # Diversity
    "unique_products",
    "unique_categories",
    "unique_sellers",

    # Intensity
    "items_per_product",
    "products_per_order",
    "sellers_per_order"
]

In [88]:
candidate_model_features = [
    # RFM / lifecycle
    "recency_days",
    "frequency",
    "monetary_value",
    "tenure_days",

    # Purchase behavior
    "total_items",
    "avg_items_per_order",
    "avg_order_value",

    # Freight behavior
    "avg_freight_per_order",
    "freight_to_merchandise_ratio",

    # Payment behavior
    "avg_payment_records_per_order",
    "max_installments",
    "avg_installments",

    # Satisfaction
    "avg_review_score",
    "review_coverage_ratio",

    # Diversity
    "unique_products",
    "unique_categories",
    "unique_sellers",

    # Intensity
    "items_per_product",
    "products_per_order",
    "sellers_per_order"
]

Identify everything not classified

In [89]:
classified = set(
    id_columns
    + date_columns
    + profiling_only_features
    + candidate_model_features
)

unclassified_features = [
    col
    for col in customer_features_clean.columns
    if col not in classified
]

print("Unclassified features:")
for col in unclassified_features:
    print("-", col)

Unclassified features:
- total_order_value
- total_freight
- avg_merchandise_per_order
- total_payment_value
- avg_payment_value
- max_payment_methods_per_order
- avg_payment_methods_per_order

Final missingness audit

In [90]:
final_missing_audit = (
    customer_features_clean
    .isna()
    .sum()
    .to_frame("missing_count")
)

final_missing_audit["missing_pct"] = (
    final_missing_audit["missing_count"]
    / len(customer_features_clean)
    * 100
)

final_missing_audit = (
    final_missing_audit[
        final_missing_audit["missing_count"] > 0
    ]
    .sort_values("missing_pct", ascending=False)
)

final_missing_audit

                               missing_count  missing_pct
avg_days_between_purchases             90557        97.00
avg_review_score                         603         0.65
total_payment_value                        1         0.00
avg_payment_value                          1         0.00
avg_payment_records_per_order              1         0.00
max_payment_methods_per_order              1         0.00
avg_payment_methods_per_order              1         0.00
max_installments                           1         0.00
avg_installments                           1         0.00

In [91]:
CUSTOMER_FEATURES_PATH = (
    DATA_PROCESSED / "customer_features.parquet"
)

customer_features_clean.to_parquet(
    CUSTOMER_FEATURES_PATH,
    index=False
)

print("Saved:", CUSTOMER_FEATURES_PATH)

Saved: C:\Users\amolm\Desktop\PROJECTS RESUME\Customer Segmentation\data\processed\customer_features.parquet

In [92]:
customer_features_test = pd.read_parquet(
    CUSTOMER_FEATURES_PATH
)

phase3_final_validation = pd.Series({
    "rows":
        len(customer_features_test),

    "columns":
        len(customer_features_test.columns),

    "unique_customers":
        customer_features_test["customer_unique_id"].nunique(),

    "duplicate_customer_ids":
        customer_features_test["customer_unique_id"]
        .duplicated()
        .sum(),

    "missing_customer_ids":
        customer_features_test["customer_unique_id"]
        .isna()
        .sum(),

    "suffix_columns":
        sum(
            col.endswith("_x") or col.endswith("_y")
            for col in customer_features_test.columns
        )
})

phase3_final_validation

rows                      93358
columns                      35
unique_customers          93358
duplicate_customer_ids        0
missing_customer_ids          0
suffix_columns                0
dtype: int64